### ISSUE TITLE
Can not get it to Install

### ISSUE THREAD

**Issue by tholum** [GetVideostream/cordova-chromecast#38]
Any help would be greatly appreicited, 

 cordova plugin add https://github.com/GetVideostream/cordova-chromecast.git
Fetching plugin "https://github.com/GetVideostream/cordova-chromecast.git" via git clone
Installing "acidhax.cordova.chromecast" for android
Found Android SDK at /opt/android-sdk-linux
Executing /opt/android-sdk-linux/tools/android update lib-project -p ./platforms/android/AppCompatLib ...
Failed to install 'acidhax.cordova.chromecast':Error: spawn EMFILE
    at errnoException (child_process.js:988:11)
    at ChildProcess.spawn (child_process.js:935:11)
    at exports.spawn (child_process.js:723:9)
    at Object.exports.execFile (child_process.js:607:15)
    at exports.exec (child_process.js:578:18)
    at execCommand (/home/tholum/Documents/Projects/MyApp/plugins/acidhax.cordova.chromecast/init-playservices-dependencies.js:44:13)
    at prepareLibraryProject (/home/tholum/Documents/Projects/MyApp/plugins/acidhax.cordova.chromecast/init-playservices-dependencies.js:73:5)
    at Object.<anonymous> (/home/tholum/Documents/Projects/MyApp/plugins/acidhax.cordova.chromecast/init-playservices-dependencies.js:170:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
Error: spawn EMFILE
    at errnoException (child_process.js:988:11)
    at ChildProcess.spawn (child_process.js:935:11)
    at exports.spawn (child_process.js:723:9)
    at Object.exports.execFile (child_process.js:607:15)
    at exports.exec (child_process.js:578:18)
    at execCommand (/home/tholum/Documents/Projects/MyApp/plugins/acidhax.cordova.chromecast/init-playservices-dependencies.js:44:13)
    at prepareLibraryProject (/home/tholum/Documents/Projects/MyApp/plugins/acidhax.cordova.chromecast/init-playservices-dependencies.js:73:5)
    at Object.<anonymous> (/home/tholum/Documents/Projects/MyApp/plugins/acidhax.cordova.chromecast/init-playservices-dependencies.js:170:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by tholum** [comment]
Same Issue on my mac ( Slightly Different result Code )

cordova plugin add https://github.com/GetVideostream/cordova-chromecast.git
Fetching plugin "https://github.com/GetVideostream/cordova-chromecast.git" via git clone
Installing "acidhax.cordova.chromecast" for android
Found Android SDK at /Users/ctl/android-sdk-macosx
Executing /Users/ctl/android-sdk-macosx/tools/android update lib-project -p ./platforms/android/AppCompatLib ...
Error: ENOENT, open '/Users/ctl/android-sdk-macosx/extras/android/support/v7/appcompat/'

**Comment by tholum** [comment]
Issue is resolved, I had to install the "extras" package in the android sdk

![image](https://cloud.githubusercontent.com/assets/2395584/5617788/02a1da74-94d8-11e4-9535-048b8301aa1f.png)
