### ISSUE TITLE
Cant able to take the build after installing our plugins.

### ISSUE THREAD

**Issue by gladsonrobinson89** [GetVideostream/cordova-chromecast#39]
I initially have installed 
Step 1: cordova plugin add https://github.com/GetVideostream/cordova-chromecast.git
Step 2: cordova plugin add https://github.com/pkaul/googleplayservices-cordova-plugin.git

After installing above plugin I cant able to take the build. 

Error am getting is.

BUILD FAILED
'/home/gladson/adt-bundle-linux-x86_64-20140702/sdk/tools/ant/build.xml:720: The following error 'occurred while executing this line:
/home/gladson/adt-bundle-linux-x86_64-20140702/sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 4 seconds

/var/www/ionic/testcast/mycast2/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/var/www/ionic/testcast/mycast2/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /var/www/ionic/testcast/mycast2/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

**Comment by gladsonrobinson89** [comment]
HI still I having the same error. Actually I need to use jwplayer cast function in my cordova app. Please help me.

**Comment by acidhax** [comment]
Could you try again?

**Comment by gladsonrobinson89** [comment]
Yes have done it again.. But still am getting the same error. 
But have used the below one and am not getting the previous error. 
cordova plugin add https://github.com/AVGP/cordova-chromecast.git

I need to know whether is it same us our plugin.
